# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Next.js site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #add env file to .env.local
      - name: Set Env Vars on Vercel Project
        uses: dkershner6/vercel-set-env-action@v1
        with:
          token: ${{ secrets.VERCEL_DEPLOY_TOKEN }}
          projectName: our-portfolio # project name in Vercel
          envVariableKeys: NOTION_TOKEN
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          TARGET_NOTION_TOKEN: preview,development,production # comma delimited, one of [production, preview, development]
          TYPE_NOTION_TOKEN: encrypted # one of [plain, encrypted]
      # deploy app to vercel
      - name: deploy site to vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_DEPLOY_TOKEN }} # Required
          vercel-org-id: ${{ secrets.ORG_ID}} #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
